services:
  - type: web
    name: gemini-qna-app
    env: node
    plan: free # Or your preferred plan
    rootDir: backend # Specify the root directory for build and start commands
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: GEMINI_API_KEY
        sync: false # CORRECT: This tells Render to manage the value in the dashboard
      - key: NODE_VERSION
        value: 18
